### ISSUE TITLE
denite-gtags doesn't work

### ISSUE THREAD

**Issue by amikai** [ozelentok/denite-gtags#3]
After install , execute every denite-gtags command get the error following.

[denite] Traceback (most recent call last):
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 29, in start

[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 68, in sta
rt
[denite]     self._start(sources, context)
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 111, in _s
tart
[denite]     self.init_denite()
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 608, in in
it_denite
[denite]     self._denite.start(self._context)
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 36, in start
[denite]     self.load_filters(context)
[denite]   File "/Users/kai/.local/share/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 222, in load_f
ilters
[denite]     'denite.filter.' + name, path).load_module()
[denite]   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
[denite]   File "<frozen importlib._bootstrap_external>", line 823, in load_module
[denite]   File "<frozen importlib._bootstrap_external>", line 682, in load_module
[denite]   File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
[denite]   File "<frozen importlib._bootstrap>", line 675, in _load
[denite]   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
[denite]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[denite]   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[denite]   File "/Users/kai/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/filter/converter_relative_abbr.
py", line 8, in <module>
[denite]     from denite.util import relpath
[denite] ImportError: cannot import name 'relpath'
[denite] Please execute :messages command.

**Comment by ozelentok** [comment]
Judging by the stack trace, the exception is coming from denite itself and not denite-gtags
Are you using the newest denite version?
Please run of denite' own commands, such as:
:Denite file_rec

**Comment by amikai** [comment]
After update, it works good. thanks.
